import { TourPackage, Testimonial, Destination, FAQ, BlogPost } from "@/types";

export const tourPackages: TourPackage[] = [
  {
    id: "1",
    title: "Bali Paradise Escape",
    destination: "Bali, Indonesia",
    duration: "5 Hari 4 Malam",
    price: 3500000,
    originalPrice: 4200000,
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    category: "domestik",
    rating: 4.9,
    reviewCount: 248,
    highlights: ["Tanah Lot", "Ubud Rice Terrace", "Kuta Beach", "Uluwatu Temple"],
    includes: ["Hotel Bintang 4", "Transportasi AC", "Guide Profesional", "Makan 3x Sehari"],
    description: "Nikmati keindahan Pulau Dewata dengan paket lengkap yang mencakup destinasi terbaik Bali.",
    badge: "Best Seller",
    isBestSeller: true,
  },
  {
    id: "2",
    title: "Labuan Bajo & Komodo Adventure",
    destination: "Labuan Bajo, NTT",
    duration: "4 Hari 3 Malam",
    price: 4800000,
    originalPrice: 5500000,
    image: "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800&q=80",
    category: "domestik",
    rating: 4.8,
    reviewCount: 156,
    highlights: ["Pulau Komodo", "Pink Beach", "Padar Island", "Snorkeling"],
    includes: ["Kapal Phinisi", "Hotel Bintang 3", "Guide Lokal", "Makan Siang"],
    description: "Jelajahi keajaiban alam Labuan Bajo dan bertemu langsung dengan Komodo Dragon.",
    badge: "Hot Deal",
    isPopular: true,
  },
  {
    id: "3",
    title: "Raja Ampat Underwater Paradise",
    destination: "Raja Ampat, Papua Barat",
    duration: "6 Hari 5 Malam",
    price: 8500000,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    category: "domestik",
    rating: 5.0,
    reviewCount: 89,
    highlights: ["Diving & Snorkeling", "Wayag Island", "Piaynemo", "Arborek Village"],
    includes: ["Resort Tepi Pantai", "Perahu Speedboat", "Instruktur Diving", "Full Board"],
    description: "Surga bawah laut terbaik di dunia menanti Anda di Raja Ampat.",
    badge: "Premium",
    isPopular: true,
  },
  {
    id: "4",
    title: "Istanbul & Cappadocia Discovery",
    destination: "Turki",
    duration: "8 Hari 7 Malam",
    price: 18500000,
    originalPrice: 22000000,
    image: "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&q=80",
    category: "internasional",
    rating: 4.9,
    reviewCount: 312,
    highlights: ["Hagia Sophia", "Hot Air Balloon", "Grand Bazaar", "Bosphorus Cruise"],
    includes: ["Hotel Bintang 4", "Tiket Pesawat PP", "Visa Turki", "Guide Berbahasa Indonesia"],
    description: "Jelajahi keindahan Turki dari Istanbul yang megah hingga Cappadocia yang menakjubkan.",
    badge: "Most Popular",
    isBestSeller: true,
  },
  {
    id: "5",
    title: "Jepang Cherry Blossom Tour",
    destination: "Jepang",
    duration: "10 Hari 9 Malam",
    price: 28000000,
    originalPrice: 32000000,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    category: "internasional",
    rating: 4.9,
    reviewCount: 445,
    highlights: ["Tokyo Disneyland", "Fuji Mountain", "Kyoto Temples", "Osaka Castle"],
    includes: ["Hotel Bintang 4", "JR Pass 7 Hari", "Tiket Pesawat PP", "Tour Manager"],
    description: "Saksikan keindahan bunga sakura yang memukau di berbagai kota bersejarah Jepang.",
    badge: "Seasonal Special",
    isPopular: true,
  },
  {
    id: "6",
    title: "Umrah Reguler Ramadhan",
    destination: "Makkah & Madinah",
    duration: "12 Hari 11 Malam",
    price: 32000000,
    image: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800&q=80",
    category: "umrah",
    rating: 5.0,
    reviewCount: 567,
    highlights: ["Masjidil Haram", "Masjid Nabawi", "Jabal Nur", "Ziarah Makkah-Madinah"],
    includes: ["Hotel Bintang 5 Dekat Haram", "Tiket Pesawat PP", "Visa Umrah", "Muthawwif Berpengalaman"],
    description: "Perjalanan ibadah umrah yang nyaman dan berkesan dengan pelayanan terbaik.",
    badge: "Terpercaya",
    isBestSeller: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Siti Rahayu",
    location: "Jakarta",
    rating: 5,
    comment: "Pengalaman luar biasa! Pelayanan Dzawani Tour sangat profesional dan ramah. Tour ke Bali kemarin benar-benar tak terlupakan. Pasti akan booking lagi!",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&q=80",
    tourPackage: "Bali Paradise Escape",
    date: "Januari 2025",
  },
  {
    id: "2",
    name: "Ahmad Fauzi",
    location: "Surabaya",
    rating: 5,
    comment: "Umrah bersama Dzawani Tour sangat berkesan. Hotel dekat Haram, pembimbing yang sabar dan berpengetahuan. Alhamdulillah, ibadah berjalan lancar.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    tourPackage: "Umrah Reguler Ramadhan",
    date: "Maret 2025",
  },
  {
    id: "3",
    name: "Dewi Kusuma",
    location: "Bandung",
    rating: 5,
    comment: "Turki sungguh indah! Hot air balloon di Cappadocia adalah momen yang tidak akan pernah saya lupakan. Terima kasih Dzawani Tour sudah membuat impian saya jadi kenyataan!",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    tourPackage: "Istanbul & Cappadocia Discovery",
    date: "April 2025",
  },
  {
    id: "4",
    name: "Budi Santoso",
    location: "Yogyakarta",
    rating: 5,
    comment: "Labuan Bajo benar-benar surga! Snorkeling di Pink Beach dan melihat Komodo langsung adalah pengalaman tak ternilai. Guide lokal Dzawani sangat informatif.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    tourPackage: "Labuan Bajo & Komodo Adventure",
    date: "Mei 2025",
  },
  {
    id: "5",
    name: "Rina Marlina",
    location: "Medan",
    rating: 5,
    comment: "Jepang di musim sakura adalah impian saya sejak lama. Dzawani Tour membuat perjalanan ini sangat terorganisir dan menyenangkan. Highly recommended!",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    tourPackage: "Jepang Cherry Blossom Tour",
    date: "April 2025",
  },
];

export const destinations: Destination[] = [
  {
    id: "1",
    name: "Bali",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80",
    packageCount: 8,
    category: "Domestik",
  },
  {
    id: "2",
    name: "Labuan Bajo",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=600&q=80",
    packageCount: 5,
    category: "Domestik",
  },
  {
    id: "3",
    name: "Turki",
    country: "Turkey",
    image: "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=600&q=80",
    packageCount: 6,
    category: "Internasional",
  },
  {
    id: "4",
    name: "Jepang",
    country: "Japan",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80",
    packageCount: 7,
    category: "Internasional",
  },
  {
    id: "5",
    name: "Makkah & Madinah",
    country: "Saudi Arabia",
    image: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=600&q=80",
    packageCount: 4,
    category: "Umrah",
  },
  {
    id: "6",
    name: "Raja Ampat",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80",
    packageCount: 3,
    category: "Domestik",
  },
];

export const faqs: FAQ[] = [
  {
    id: "1",
    question: "Bagaimana cara memesan paket tour di Dzawani Tour?",
    answer: "Anda dapat memesan paket tour melalui website kami, menghubungi WhatsApp kami, atau datang langsung ke kantor kami. Proses pemesanan sangat mudah dan tim kami siap membantu Anda.",
    category: "Pemesanan",
  },
  {
    id: "2",
    question: "Berapa lama sebelumnya saya harus memesan paket tour?",
    answer: "Kami menyarankan pemesanan minimal 2-4 minggu sebelum keberangkatan untuk paket domestik, dan 1-3 bulan untuk paket internasional. Untuk umrah, pemesanan sebaiknya dilakukan 3-6 bulan sebelumnya.",
    category: "Pemesanan",
  },
  {
    id: "3",
    question: "Apakah harga sudah termasuk tiket pesawat?",
    answer: "Tergantung paket yang Anda pilih. Beberapa paket sudah include tiket pesawat PP, sementara yang lain belum. Detail inclusi tercantum jelas di setiap halaman paket tour.",
    category: "Harga",
  },
  {
    id: "4",
    question: "Apakah ada garansi keberangkatan?",
    answer: "Ya, kami memberikan garansi keberangkatan untuk semua paket yang sudah mencapai kuota minimum. Jika terjadi pembatalan dari pihak kami, uang akan dikembalikan 100%.",
    category: "Jaminan",
  },
  {
    id: "5",
    question: "Bagaimana kebijakan pembatalan dan refund?",
    answer: "Pembatalan lebih dari 30 hari sebelum keberangkatan: refund 80%. 15-30 hari: refund 50%. Kurang dari 15 hari: refund 25%. Pembatalan karena force majeure akan dipertimbangkan secara khusus.",
    category: "Kebijakan",
  },
  {
    id: "6",
    question: "Apakah tersedia paket untuk grup atau keluarga?",
    answer: "Tentu! Kami menyediakan paket khusus grup (minimal 10 orang) dengan harga lebih terjangkau dan dapat dikustomisasi sesuai kebutuhan. Hubungi kami untuk mendapatkan penawaran terbaik.",
    category: "Paket",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "10 Destinasi Wisata Terbaik Indonesia yang Wajib Dikunjungi 2025",
    excerpt: "Indonesia menyimpan keindahan alam yang luar biasa. Dari Sabang sampai Merauke, temukan destinasi terbaik yang sayang untuk dilewatkan.",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80",
    author: "Tim Dzawani Tour",
    date: "15 Januari 2025",
    category: "Destinasi",
    readTime: "5 menit",
  },
  {
    id: "2",
    title: "Tips Persiapan Umrah yang Perlu Anda Ketahui",
    excerpt: "Persiapan yang matang adalah kunci ibadah umrah yang lancar dan berkesan. Simak tips lengkap dari tim Dzawani Tour.",
    image: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=600&q=80",
    author: "Ustadz Ahmad",
    date: "20 Februari 2025",
    category: "Umrah",
    readTime: "7 menit",
  },
  {
    id: "3",
    title: "Panduan Lengkap Wisata ke Jepang: Musim, Visa, dan Itinerary",
    excerpt: "Jepang adalah destinasi impian banyak wisatawan Indonesia. Pelajari semua yang perlu Anda ketahui sebelum berangkat.",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80",
    author: "Sarah Wanderlust",
    date: "5 Maret 2025",
    category: "Internasional",
    readTime: "10 menit",
  },
];

export const stats = [
  { label: "Wisatawan Puas", value: "15,000+", icon: "users" },
  { label: "Destinasi Tersedia", value: "50+", icon: "map" },
  { label: "Tahun Pengalaman", value: "10+", icon: "calendar" },
  { label: "Penghargaan", value: "25+", icon: "award" },
];
