import { TourPackage, Testimonial, Destination, FAQ } from "@/types";

export const tourPackages: TourPackage[] = [
  {
    id: "1",
    title: "Bali Paradise Escape",
    destination: "Bali, Indonesia",
    duration: "5 Hari 4 Malam",
    price: 3500000,
    originalPrice: 4200000,
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    category: "domestik",
    rating: 4.9,
    reviewCount: 248,
    highlights: ["Tanah Lot", "Ubud Rice Terrace", "Kuta Beach", "Uluwatu Temple"],
    includes: ["Hotel Bintang 4", "Transportasi AC", "Guide Profesional", "Makan 3x Sehari"],
    description: "Nikmati keindahan Pulau Dewata dengan paket lengkap yang mencakup destinasi terbaik Bali.",
    badge: "Best Seller",
    isBestSeller: true,
  },
  {
    id: "2",
    title: "Labuan Bajo & Komodo Adventure",
    destination: "Labuan Bajo, NTT",
    duration: "4 Hari 3 Malam",
    price: 4800000,
    originalPrice: 5500000,
    image: "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800&q=80",
    category: "domestik",
    rating: 4.8,
    reviewCount: 156,
    highlights: ["Pulau Komodo", "Pink Beach", "Padar Island", "Snorkeling"],
    includes: ["Kapal Phinisi", "Hotel Bintang 3", "Guide Lokal", "Makan Siang"],
    description: "Jelajahi keajaiban alam Labuan Bajo dan bertemu langsung dengan Komodo Dragon.",
    badge: "Hot Deal",
    isPopular: true,
  },
  {
    id: "3",
    title: "Raja Ampat Underwater Paradise",
    destination: "Raja Ampat, Papua Barat",
    duration: "6 Hari 5 Malam",
    price: 8500000,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    category: "domestik",
    rating: 5.0,
    reviewCount: 89,
    highlights: ["Diving & Snorkeling", "Wayag Island", "Piaynemo", "Arborek Village"],
    includes: ["Resort Tepi Pantai", "Perahu Speedboat", "Instruktur Diving", "Full Board"],
    description: "Surga bawah laut terbaik di dunia menanti Anda di Raja Ampat.",
    badge: "Premium",
    isPopular: true,
  },
  {
    id: "4",
    title: "Istanbul & Cappadocia Discovery",
    destination: "Turki",
    duration: "8 Hari 7 Malam",
    price: 18500000,
    originalPrice: 22000000,
    image: "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&q=80",
    category: "internasional",
    rating: 4.9,
    reviewCount: 312,
    highlights: ["Hagia Sophia", "Hot Air Balloon", "Grand Bazaar", "Bosphorus Cruise"],
    includes: ["Hotel Bintang 4", "Tiket Pesawat PP", "Visa Turki", "Guide Berbahasa Indonesia"],
    description: "Jelajahi keindahan Turki dari Istanbul yang megah hingga Cappadocia yang menakjubkan.",
    badge: "Most Popular",
    isBestSeller: true,
  },
  {
    id: "5",
    title: "Jepang Cherry Blossom Tour",
    destination: "Jepang",
    duration: "10 Hari 9 Malam",
    price: 28000000,
    originalPrice: 32000000,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    category: "internasional",
    rating: 4.9,
    reviewCount: 445,
    highlights: ["Tokyo Disneyland", "Fuji Mountain", "Kyoto Temples", "Osaka Castle"],
    includes: ["Hotel Bintang 4", "JR Pass 7 Hari", "Tiket Pesawat PP", "Tour Manager"],
    description: "Saksikan keindahan bunga sakura yang memukau di berbagai kota bersejarah Jepang.",
    badge: "Seasonal Special",
    isPopular: true,
  },
];

// Open Trip Data
export const openTripDomestik = [
  {
    id: "ot-d1",
    destinasi: "Bali",
    durasi: "5H 4M",
    tanggalBerangkat: "15 Maret 2025",
    harga: 3500000,
    kuota: 20,
    tersisa: 8,
    status: "Tersedia",
    includes: "Hotel, Transport, Guide, Makan",
  },
  {
    id: "ot-d2",
    destinasi: "Labuan Bajo",
    durasi: "4H 3M",
    tanggalBerangkat: "22 Maret 2025",
    harga: 4800000,
    kuota: 15,
    tersisa: 5,
    status: "Hampir Penuh",
    includes: "Kapal Phinisi, Hotel, Guide, Makan",
  },
  {
    id: "ot-d3",
    destinasi: "Raja Ampat",
    durasi: "6H 5M",
    tanggalBerangkat: "1 April 2025",
    harga: 8500000,
    kuota: 12,
    tersisa: 12,
    status: "Tersedia",
    includes: "Resort, Speedboat, Diving, Full Board",
  },
  {
    id: "ot-d4",
    destinasi: "Lombok & Gili",
    durasi: "4H 3M",
    tanggalBerangkat: "10 April 2025",
    harga: 3200000,
    kuota: 20,
    tersisa: 14,
    status: "Tersedia",
    includes: "Hotel, Fast Boat, Guide, Makan",
  },
  {
    id: "ot-d5",
    destinasi: "Yogyakarta",
    durasi: "3H 2M",
    tanggalBerangkat: "18 April 2025",
    harga: 1800000,
    kuota: 25,
    tersisa: 20,
    status: "Tersedia",
    includes: "Hotel, Transport, Guide",
  },
  {
    id: "ot-d6",
    destinasi: "Bromo & Ijen",
    durasi: "3H 2M",
    tanggalBerangkat: "25 April 2025",
    harga: 2200000,
    kuota: 18,
    tersisa: 3,
    status: "Hampir Penuh",
    includes: "Jeep, Hotel, Guide, Makan Pagi",
  },
];

export const openTripInternasional = [
  {
    id: "ot-i1",
    destinasi: "Turki (Istanbul & Cappadocia)",
    durasi: "8H 7M",
    tanggalBerangkat: "20 Maret 2025",
    harga: 18500000,
    kuota: 15,
    tersisa: 6,
    status: "Hampir Penuh",
    includes: "Hotel, Pesawat PP, Visa, Guide",
  },
  {
    id: "ot-i2",
    destinasi: "Jepang (Tokyo & Kyoto)",
    durasi: "10H 9M",
    tanggalBerangkat: "1 April 2025",
    harga: 28000000,
    kuota: 20,
    tersisa: 11,
    status: "Tersedia",
    includes: "Hotel, Pesawat PP, JR Pass, Guide",
  },
  {
    id: "ot-i3",
    destinasi: "Korea Selatan",
    durasi: "7H 6M",
    tanggalBerangkat: "15 April 2025",
    harga: 22000000,
    kuota: 18,
    tersisa: 9,
    status: "Tersedia",
    includes: "Hotel, Pesawat PP, Visa, Guide",
  },
  {
    id: "ot-i4",
    destinasi: "Eropa (Paris & Amsterdam)",
    durasi: "12H 11M",
    tanggalBerangkat: "5 Mei 2025",
    harga: 45000000,
    kuota: 15,
    tersisa: 7,
    status: "Tersedia",
    includes: "Hotel, Pesawat PP, Visa Schengen, Guide",
  },
  {
    id: "ot-i5",
    destinasi: "Dubai & Abu Dhabi",
    durasi: "6H 5M",
    tanggalBerangkat: "20 Mei 2025",
    harga: 19500000,
    kuota: 20,
    tersisa: 15,
    status: "Tersedia",
    includes: "Hotel, Pesawat PP, Desert Safari, Guide",
  },
];

// Private Trip Data
export const privateTripDomestik = [
  {
    id: "pt-d1",
    destinasi: "1 D - HAPPYLAND TOUR",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1250000,
    hargaPer4Pax: 1030000,
    hargaPer6Pax: 900000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d2",
    destinasi: "1 D - SKY VIEW LEMBANG",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1600000,
    hargaPer4Pax: 1105000,
    hargaPer6Pax: 705000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d3",
    destinasi: "1 D - BANDUNG STREET VIBES",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1100000,
    hargaPer4Pax: 885000,
    hargaPer6Pax: 835000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Refreshment, Parkir objek wisata, Tour Leader & Local Guide",
  },
  {
    id: "pt-d4",
    destinasi: "1 D - MUSEUM & MONUMEN EXPLORER",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 900000,
    hargaPer4Pax: 650000,
    hargaPer6Pax: 480000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d5",
    destinasi: "1 D - NUANU & PURI EXPERIENCE",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 910000,
    hargaPer4Pax: 670000,
    hargaPer6Pax: 515000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d6",
    destinasi: "1 D - PURI HERITAGE TOUR",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 900000,
    hargaPer4Pax: 645000,
    hargaPer6Pax: 465000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d7",
    destinasi: "1 D - BALI SECRET ESCAPE",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1580000,
    hargaPer4Pax: 1335000,
    hargaPer6Pax: 1200000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d8",
    destinasi: "1 D - Soul Bali Trip",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1220000,
    hargaPer4Pax: 990000,
    hargaPer6Pax: 850000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d9",
    destinasi: "1 D - HIDDEN CULTURE TRIP",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1020000,
    hargaPer4Pax: 845000,
    hargaPer6Pax: 635000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d10",
    destinasi: "1 D - EXPLORE LEMBANG GREEN",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1900000,
    hargaPer4Pax: 1255000,
    hargaPer6Pax: 690000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d11",
    destinasi: "1 D - HARMONY OF HERITAGE",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1110000,
    hargaPer4Pax: 860000,
    hargaPer6Pax: 695000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d12",
    destinasi: "1 D - CAFE & STREET TOUR",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 910000,
    hargaPer4Pax: 655000,
    hargaPer6Pax: 475000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d13",
    destinasi: "1 D - SOUND TRIP",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1410000,
    hargaPer4Pax: 1210000,
    hargaPer6Pax: 1125000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d14",
    destinasi: "1 D - COFFEE WORKSHOP BALI",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 999000,
    hargaPer4Pax: 610000,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d15",
    destinasi: "1 D - TRIP BUDAYA",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 970000,
    hargaPer4Pax: 620000,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d16",
    destinasi: "1 D - BALI SUNSET",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1360000,
    hargaPer4Pax: 1210000,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d17",
    destinasi: "1 D - TRIP ADVENTURE",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 910000,
    hargaPer4Pax: 695000,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d18",
    destinasi: "1 D - TRIP SHOPPING",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 800000,
    hargaPer4Pax: 400000,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d19",
    destinasi: "1 D - TRIP GOA PINDUL",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 770000,
    hargaPer4Pax: 550000,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d20",
    destinasi: "1 D - WORKSHOP SILVER - BALI",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1290000,
    hargaPer4Pax: 860000,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  },
  {
    id: "pt-d21",
    destinasi: "4D 3N BANDUNG - PANGALENGAN - CIWIDEY",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d22",
    destinasi: "4D 3N - C BANDUNG - LEMBANG - PANGALENGAN - CIWIDEY",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d23",
    destinasi: "3D2N (LEMBANG - BANDUNG)",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d24",
    destinasi: "4D3N - B - BANDUNG - LEMBANG - PANGALENGAN",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d25",
    destinasi: "4D3N- A - BANDUNG - LEMBANG – CIWIDEY",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d26",
    destinasi: "3D2N - LEMBANG - PANGALENGAN",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d27",
    destinasi: "3D2N - LEMBANG - CIWIDEY - TANGKUBAN PERAHU",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d28",
    destinasi: "3D2N BANDUNG - CIWIDEY - LEMBANG",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d29",
    destinasi: "3D2N - PANGALENGAN (BODY RAFTING)",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d30",
    destinasi: "BANDUNG PANGALENGAN (BODY RAFTING+ OFFROAD)",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d31",
    destinasi: "BANDUNG PANGALENGAN (BODY RAFTING)",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d32",
    destinasi: "SIGNATURE B BANDUNG UTARA - LEMBANG",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d33",
    destinasi: "SIGNATURE A (BANDUNG SELATAN) CIWIDEY - KAWAH PUTIH",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d34",
    destinasi: "PAKET WISATA 2D1N - SIGNATURE BANDUNG SELATAN",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d35",
    destinasi: "NAMA PAKET : SIGNATURE MIX BANDUNG - TANGKUBAN PERAHU",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d36",
    destinasi: "NAMA PAKET : TOUR 2DIN - SIGNATURE BANDUNG UTARA",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d37",
    destinasi: "NAME PACKAGE : 2D1N BANDUNG CIWIDEY",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d38",
    destinasi: "NAMA PEKET: TOUR 1 HARI BANDUNG - LEMBANG",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d39",
    destinasi: "NAMA PEKET: TOUR 1 HARI BANDUNG - LEMBANG",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d40",
    destinasi: "NAMA PEKET: TOUR 1 HARI BANDUNG - PANGALENGAN",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d41",
    destinasi: "NAMA PEKET: TOUR 1 HARI BANDUNG SELATAN - CIWIDEY",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 0,
    hargaPer4Pax: 0,
    hargaPer6Pax: 0,
    status: "Tersedia",
    includes: "Hotel, Transport Private, Guide, Makan",
  },
  {
    id: "pt-d42",
    destinasi: "1 D - JOGYA SIGNATURE TRIP",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 1000000,
    hargaPer4Pax: 750000,
    hargaPer6Pax: 535000,
    status: "Tersedia",
    includes: "Transportasi Bus Pariwisata AC, Tiket Masuk objek wisata, Refreshment, Parkir objek wisata",
  }
];


export const privateTripInternasional = [
  {
    id: "pt-i1",
    destinasi: "Turki (Istanbul & Cappadocia)",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 28000000,
    hargaPer4Pax: 22000000,
    hargaPer6Pax: 19000000,
    status: "Tersedia",
    includes: "Hotel, Pesawat PP, Visa, Guide Private",
  },
  {
    id: "pt-i2",
    destinasi: "Jepang",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 38000000,
    hargaPer4Pax: 32000000,
    hargaPer6Pax: 28000000,
    status: "Tersedia",
    includes: "Hotel, Pesawat PP, JR Pass, Guide Private",
  },
  {
    id: "pt-i3",
    destinasi: "Korea Selatan",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 30000000,
    hargaPer4Pax: 25000000,
    hargaPer6Pax: 22000000,
    status: "Tersedia",
    includes: "Hotel, Pesawat PP, Visa, Guide Private",
  },
  {
    id: "pt-i4",
    destinasi: "Eropa (Paris & Amsterdam)",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 65000000,
    hargaPer4Pax: 55000000,
    hargaPer6Pax: 48000000,
    status: "Tersedia",
    includes: "Hotel, Pesawat PP, Visa Schengen, Guide Private",
  },
  {
    id: "pt-i5",
    destinasi: "Dubai & Abu Dhabi",
    durasi: "Fleksibel",
    minPax: "2 Orang",
    hargaPer2Pax: 28000000,
    hargaPer4Pax: 23000000,
    hargaPer6Pax: 20000000,
    status: "Tersedia",
    includes: "Hotel, Pesawat PP, Desert Safari Private, Guide",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Siti Rahayu",
    location: "Jakarta",
    rating: 5,
    comment: "Pengalaman luar biasa! Pelayanan Dzawani Tour sangat profesional dan ramah. Tour ke Bali kemarin benar-benar tak terlupakan. Pasti akan booking lagi!",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&q=80",
    tourPackage: "Bali Paradise Escape",
    date: "Januari 2025",
  },
  {
    id: "2",
    name: "Ahmad Fauzi",
    location: "Surabaya",
    rating: 5,
    comment: "Umrah bersama Dzawani Tour sangat berkesan. Hotel dekat Haram, pembimbing yang sabar dan berpengetahuan. Alhamdulillah, ibadah berjalan lancar.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    tourPackage: "Open Trip Turki",
    date: "Maret 2025",
  },
  {
    id: "3",
    name: "Dewi Kusuma",
    location: "Bandung",
    rating: 5,
    comment: "Turki sungguh indah! Hot air balloon di Cappadocia adalah momen yang tidak akan pernah saya lupakan. Terima kasih Dzawani Tour!",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    tourPackage: "Open Trip Istanbul & Cappadocia",
    date: "April 2025",
  },
  {
    id: "4",
    name: "Budi Santoso",
    location: "Yogyakarta",
    rating: 5,
    comment: "Private trip ke Labuan Bajo bersama keluarga sangat berkesan. Pelayanan personal dan fleksibel sesuai keinginan kami.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    tourPackage: "Private Trip Labuan Bajo",
    date: "Mei 2025",
  },
  {
    id: "5",
    name: "Rina Marlina",
    location: "Medan",
    rating: 5,
    comment: "Jepang di musim sakura adalah impian saya sejak lama. Dzawani Tour membuat perjalanan ini sangat terorganisir dan menyenangkan. Highly recommended!",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    tourPackage: "Open Trip Jepang Cherry Blossom",
    date: "April 2025",
  },
];

export const destinations: Destination[] = [
  {
    id: "1",
    name: "Bali",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80",
    packageCount: 8,
    category: "Domestik",
  },
  {
    id: "2",
    name: "Labuan Bajo",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=600&q=80",
    packageCount: 5,
    category: "Domestik",
  },
  {
    id: "3",
    name: "Turki",
    country: "Turkey",
    image: "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=600&q=80",
    packageCount: 6,
    category: "Internasional",
  },
  {
    id: "4",
    name: "Jepang",
    country: "Japan",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80",
    packageCount: 7,
    category: "Internasional",
  },
  {
    id: "5",
    name: "Raja Ampat",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80",
    packageCount: 3,
    category: "Domestik",
  },
];

export const faqs: FAQ[] = [
  {
    id: "1",
    question: "Apa perbedaan Open Trip dan Private Trip?",
    answer: "Open Trip adalah paket wisata bersama dengan peserta lain (grup gabungan) dengan harga lebih terjangkau dan jadwal keberangkatan yang sudah ditentukan. Private Trip adalah paket wisata eksklusif khusus untuk Anda dan rombongan sendiri, dengan jadwal dan itinerary yang dapat disesuaikan.",
    category: "Umum",
  },
  {
    id: "2",
    question: "Bagaimana cara memesan paket tour di Dzawani Tour?",
    answer: "Anda dapat memesan melalui: (1) Halaman website ini dengan klik tombol 'Pesan Sekarang', (2) WhatsApp kami di +62 812-3456-7890, atau (3) Datang langsung ke kantor kami. Tim kami siap membantu proses pemesanan Anda.",
    category: "Pemesanan",
  },
  {
    id: "3",
    question: "Berapa lama sebelumnya saya harus memesan?",
    answer: "Untuk Open Trip domestik: minimal 7-14 hari sebelum keberangkatan. Open Trip internasional: minimal 1 bulan. Private Trip: minimal 2 minggu untuk domestik, 1-2 bulan untuk internasional. Pemesanan lebih awal sangat disarankan karena kuota terbatas.",
    category: "Pemesanan",
  },
  {
    id: "4",
    question: "Apakah harga sudah termasuk tiket pesawat?",
    answer: "Untuk paket internasional, harga sudah termasuk tiket pesawat PP (pulang-pergi). Untuk paket domestik, tiket pesawat tidak termasuk kecuali disebutkan secara khusus. Detail inclusi tercantum di setiap paket.",
    category: "Harga",
  },
  {
    id: "5",
    question: "Bagaimana sistem pembayaran?",
    answer: "Pembayaran dapat dilakukan melalui transfer bank (BCA, Mandiri, BNI, BRI) atau tunai di kantor kami. Untuk konfirmasi booking, diperlukan DP minimal 30% dari total harga. Pelunasan dilakukan paling lambat 14 hari sebelum keberangkatan.",
    category: "Pembayaran",
  },
  {
    id: "6",
    question: "Apa kebijakan pembatalan dan refund?",
    answer: "Pembatalan lebih dari 30 hari sebelum keberangkatan: refund 80%. Pembatalan 15-30 hari sebelumnya: refund 50%. Pembatalan kurang dari 15 hari: refund 25%. Pembatalan karena force majeure (bencana alam, pandemi) akan dipertimbangkan secara khusus.",
    category: "Kebijakan",
  },
  {
    id: "7",
    question: "Apakah tersedia paket untuk grup atau keluarga?",
    answer: "Tentu! Private Trip sangat cocok untuk grup keluarga atau perusahaan. Untuk Open Trip grup (minimal 10 orang), kami menyediakan harga khusus dan dapat mengatur jadwal keberangkatan tersendiri. Hubungi kami untuk penawaran terbaik.",
    category: "Paket",
  },
  {
    id: "8",
    question: "Apakah ada asuransi perjalanan?",
    answer: "Ya, semua paket tour Dzawani Tour sudah dilengkapi dengan asuransi perjalanan dasar. Untuk perlindungan lebih komprehensif, kami menyarankan penambahan asuransi premium yang dapat didiskusikan saat pemesanan.",
    category: "Jaminan",
  },
];

export const stats = [
  { label: "Wisatawan Puas", value: "15,000+", icon: "users" },
  { label: "Destinasi Tersedia", value: "50+", icon: "map" },
  { label: "Tahun Pengalaman", value: "10+", icon: "calendar" },
  { label: "Penghargaan", value: "25+", icon: "award" },
];
